id: P009477
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD98
  title: འབྲིང་རིམ་དགེ་རྒན་གྱི་བོད་ཡིག་རྒྱུགས་ལེན་ཚད་གཞི་དོན་ལྡན་ཚངས་ཐིག
  author: ''
  volumes:
    86765dad839b4630a28c99447bb017fd:
      image_group_id: I1PD468
      title: ''
      volume_number: 1
      total_pages: 430
